#!/usr/bin/env bash

# set -v
# set -x

# INSTANCE=$(screen -li | grep elastic | sed 's/\s/ /g')

# if [ -n "$INSTANCE" ]
# then
    # echo "Already running: $INSTANCE"
# else
    # mkdir -p /vagrant/logs

    # screen -S elastic -d -m bash -l -c "elasticsearch -Des.config=/vagrant/conf/elasticsearch-$VM_NAME.yml > /vagrant/logs/elasticsearch-$VM_NAME.log 2>&1"
    # echo "-----------------------------------------------------------------------------------------------------------"
    # echo " => Started $VM_NAME - $VM_NODE_NAME - $VM_NODE_IP: $(screen -li | grep elastic | sed 's/\s/ /g')"
    # echo "-----------------------------------------------------------------------------------------------------------"
# fi

# New clean start method (Avoid using screen environment)
echo "### NOT starting on installation, Configure elasticsearch service to start automatically using systemd"
echo " sudo systemctl daemon-reload"
sudo systemctl daemon-reload
echo " sudo systemctl enable elasticsearch.service"
sudo systemctl enable elasticsearch.service
echo "### You can start elasticsearch service by executing"
echo " sudo systemctl start elasticsearch.service"
sudo systemctl start elasticsearch.service
